# frozen_string_literal: true

# Verifies this gem against a token minted by the real MyETM code path.
#
# Every other spec in this file tree signs its own tokens, which means they can only ever prove the
# decoder agrees with itself. This one decodes a fixture generated by MyETM
# (my-etm spec/requests/token_contract_spec.rb), so a change to how tokens are minted shows up here
# — and therefore in ETEngine and ETModel, which both verify through this decoder.
#
# When MyETM regenerates its fixture, copy it to spec/fixtures/token_contract.json. If this spec
# then fails, the token change is breaking for every Rails consumer.
RSpec.describe 'Token contract with MyETM' do
  let(:contract) do
    JSON.parse(File.read(File.expand_path('../fixtures/token_contract.json', __dir__)))
  end

  include ActiveSupport::Testing::TimeHelpers

  around do |example|
    # The fixture's tokens carry a real expiry, so decode them as of the moment they were minted.
    travel_to(Time.at(contract['generated_at'])) { example.run }
  end

  before do
    Identity.config.issuer = contract['issuer']
    # Any one of the audiences the session cookie targets; ETEngine and ETModel each match a
    # different entry in that list.
    Identity.config.client_uri = contract['session_audience'].first

    allow(Identity::TokenDecoder).to receive(:jwk_set).and_return(contract['jwks'])
  end

  after { Identity.reset_config }

  it 'accepts the session token MyETM mints' do
    expect { Identity::TokenDecoder.decode(contract['session_token']) }.not_to raise_error
  end

  it 'reads the subject from it' do
    expect(Identity::TokenDecoder.decode(contract['session_token'])['sub']).to be_present
  end

  it 'accepts it for every app in its audience' do
    contract['session_audience'].each do |audience|
      Identity.config.client_uri = audience

      expect { Identity::TokenDecoder.decode(contract['session_token']) }
        .not_to(raise_error, "expected the session token to be accepted for #{audience}")
    end
  end

  # Identity::User derives roles from user.admin precisely because there is no roles claim. If the
  # provider ever starts emitting one, this fails and the derivation should be revisited.
  it 'carries authorisation as the user.admin flag, not a roles claim' do
    claims = Identity::TokenDecoder.decode(contract['session_token'])

    expect(claims).not_to have_key('roles')
    expect(claims['user']).to have_key('admin')
  end

  it 'builds an Identity::User whose admin status matches the flag' do
    claims = Identity::TokenDecoder.decode(contract['session_token'])

    expect(Identity::User.from_jwt_claims(claims).admin?).to eq(claims['user']['admin'])
  end

  it 'rejects it for an app outside its audience' do
    Identity.config.client_uri = 'https://not-an-etm-app.example.com'

    expect { Identity::TokenDecoder.decode(contract['session_token']) }
      .to raise_error(Identity::TokenDecoder::DecodeError)
  end

  # TRANSITIONAL — this and the fixture's legacy_token go when the planned API break invalidates
  # every pre-migration personal access token. See TokenDecoder#verify_audience!.
  describe 'a token in the pre-migration shape' do
    it 'still verifies, so PATs issued before the cutover keep working' do
      expect { Identity::TokenDecoder.decode(contract['legacy_token']) }.not_to raise_error
    end

    it 'resolves its legacy kid against the published JWKS' do
      legacy_kid = JWT.decode(contract['legacy_token'], nil, false).last['kid']

      expect(contract['jwks']['keys'].map { |key| key['kid'] }).to include(legacy_kid)
    end
  end
end
